alias gs='git status -s'
alias ga='git add'
alias gaa='git add .'
alias gu='git push'
alias gd='git pull'
alias gc='git commit'
alias gcm='git commit -m'
alias gi='git init'
alias gg='git diff'
alias gl='git log --graph --oneline --decorate --all'
alias nah="git reset --hard; git clean -df;"
alias gundo="git reset HEAD~"
alias gco='git checkout'
