alias dc='docker-compose'
alias dcu='docker-compose up'
alias dcb='docker-compose build'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias drm='docker rm'
alias drma='docker rm $(docker ps -aq)'
alias drmai='docker rmi $(docker images -q)'
